from __future__ import annotations
from typing import Protocol
from university_ai.llm.models import LlmRequest, LlmResponse

class LlmEngine(Protocol):
    def availability(self) -> bool: ...
    def model_info(self) -> dict[str, object]: ...
    def generate(self, request: LlmRequest) -> LlmResponse: ...
    def shutdown(self) -> None: ...
